import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";

import {
  Ban,
  Check,
  Mail,
  Play,
  RefreshCw,
  ShieldCheck,
  UserCheck,
  Workflow,
  X,
} from "lucide-react";

import {
  getSOARActions,
  getSOARHealth,
  approveSOARAction,
  rejectSOARAction,
  executeSOARAction,
} from "../services/dashboardApi";

import {
  AppShell,
  Badge,
  Button,
  Card,
  EmptyState,
  InfoRow,
  LoadingState,
  Notice,
  PageHeader,
  Panel,
  SearchInput,
  SegmentedControl,
  SidePanel,
  StatCard,
  StatusBadge,
} from "../components/ui";

/* =========================================================
   HELPERS  (unchanged — response unwrapping + normalisation)
========================================================= */

function unwrapResponse(response) {
  if (!response) return null;

  if (response.data !== undefined) {
    return response.data;
  }

  return response;
}

function getArrayFromResponse(response) {
  const data = unwrapResponse(response);

  if (Array.isArray(data)) return data;

  if (Array.isArray(data?.actions)) return data.actions;
  if (Array.isArray(data?.results)) return data.results;
  if (Array.isArray(data?.items)) return data.items;
  if (Array.isArray(data?.data)) return data.data;

  return [];
}

function getValue(object, keys, fallback = "") {
  for (const key of keys) {
    const value = object?.[key];

    if (value !== undefined && value !== null && value !== "") {
      return value;
    }
  }

  return fallback;
}

function toNumber(value, fallback = 0) {
  const number = Number(value);
  return Number.isFinite(number) ? number : fallback;
}

function toText(value, fallback = "—") {
  if (value === undefined || value === null || value === "") {
    return fallback;
  }

  if (typeof value === "object") {
    return JSON.stringify(value);
  }

  return String(value);
}

function normalizeStatus(value) {
  const status = String(value || "").toLowerCase();

  if (
    status.includes("pause") ||
    status.includes("disabled") ||
    status.includes("inactive")
  ) {
    return "Paused";
  }

  if (
    status.includes("approve") ||
    status.includes("pending") ||
    status.includes("review")
  ) {
    return "Pending";
  }

  if (
    status.includes("complete") ||
    status.includes("execut") ||
    status.includes("success")
  ) {
    return "Executed";
  }

  return "Active";
}

function normalizeCategory(value) {
  const category = String(value || "").toLowerCase();

  if (category.includes("network") || category.includes("ip")) {
    return "Network Security";
  }

  if (
    category.includes("identity") ||
    category.includes("account") ||
    category.includes("user")
  ) {
    return "Identity Security";
  }

  if (
    category.includes("notification") ||
    category.includes("email") ||
    category.includes("notify")
  ) {
    return "Notifications";
  }

  return "Endpoint Response";
}

function getIconForCategory(category) {
  if (category === "Network Security") return Ban;
  if (category === "Identity Security") return UserCheck;
  if (category === "Notifications") return Mail;

  return ShieldCheck;
}

function normalizeActions(value) {
  if (Array.isArray(value)) {
    return value.map((item) => {
      if (typeof item === "string") return item;

      return toText(
        getValue(item, ["name", "action", "type", "description"], "Response action")
      );
    });
  }

  if (typeof value === "string" && value.trim()) {
    return value
      .split(/[,|\n]/)
      .map((item) => item.trim())
      .filter(Boolean);
  }

  return [];
}

function normalizeWorkflow(item, index) {
  const category = normalizeCategory(
    getValue(item, ["category", "type", "action_type", "module"])
  );

  const rawStatus = getValue(item, [
    "status",
    "state",
    "approval_status",
    "execution_status",
  ]);

  const runs = toNumber(
    getValue(item, [
      "runs",
      "executions",
      "execution_count",
      "total_executions",
      "run_count",
    ]),
    0
  );

  const successRate = toNumber(
    getValue(item, ["successRate", "success_rate", "success_percentage"]),
    0
  );

  const actions = normalizeActions(
    getValue(item, ["actions", "response_actions", "steps", "playbook_steps"])
  );

  return {
    ...item,
    id: toText(
      getValue(item, ["id", "action_id", "playbook_id", "workflow_id"]),
      `SOAR-${String(index + 1).padStart(3, "0")}`
    ),
    name: toText(
      getValue(item, [
        "name",
        "title",
        "action_name",
        "playbook_name",
        "workflow_name",
      ]),
      `SOAR Response Action ${index + 1}`
    ),
    description: toText(
      getValue(item, ["description", "summary", "details"]),
      "Security response action generated by the SOAR engine."
    ),
    category,
    trigger: toText(
      getValue(item, [
        "trigger",
        "trigger_type",
        "event_type",
        "alert_type",
        "condition",
      ]),
      "Security alert"
    ),
    actions:
      actions.length > 0
        ? actions
        : ["Review security alert", "Execute response action", "Record result"],
    status: normalizeStatus(rawStatus),
    runs,
    lastRun: toText(
      getValue(item, ["lastRun", "last_run", "executed_at", "updated_at"]),
      "Not executed yet"
    ),
    successRate,
    icon: getIconForCategory(category),
    rawStatus: rawStatus || "",
    approvedBy: getValue(item, ["approved_by", "approvedBy"]),
    approvalNote: getValue(item, ["approval_note", "approvalNote"]),
    result: getValue(item, ["result", "execution_result", "message"]),
  };
}

/* Category colour is informational: it tells an analyst which control plane
   an action touches before they read the name. */
const CATEGORY_TONE = {
  "Endpoint Response": "indigo",
  "Network Security": "violet",
  Notifications: "amber",
  "Identity Security": "emerald",
};

export default function Automation() {
  const navigate = useNavigate();

  const [workflows, setWorkflows] = useState([]);
  const [selectedWorkflow, setSelectedWorkflow] = useState(null);

  const [search, setSearch] = useState("");
  const [category, setCategory] = useState("All");

  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState("");

  const [health, setHealth] = useState(null);
  const [healthError, setHealthError] = useState("");

  const [actionLoading, setActionLoading] = useState("");
  const [actionMessage, setActionMessage] = useState("");
  const [actionError, setActionError] = useState("");

  const loadSOARData = async (showRefreshState = false) => {
    if (showRefreshState) {
      setRefreshing(true);
    } else {
      setLoading(true);
    }

    setError("");
    setHealthError("");

    try {
      const [actionsResponse, healthResponse] = await Promise.allSettled([
        getSOARActions(),
        getSOARHealth(),
      ]);

      if (actionsResponse.status === "fulfilled") {
        const normalized = getArrayFromResponse(actionsResponse.value).map(
          normalizeWorkflow
        );

        setWorkflows(normalized);

        setSelectedWorkflow((current) => {
          if (!current) return null;

          return (
            normalized.find((workflow) => workflow.id === current.id) || null
          );
        });
      } else {
        setError(
          actionsResponse.reason?.message ||
            "Unable to load SOAR actions from the backend."
        );
      }

      if (healthResponse.status === "fulfilled") {
        setHealth(unwrapResponse(healthResponse.value));
      } else {
        setHealthError("SOAR health status unavailable.");
      }
    } catch (requestError) {
      setError(
        requestError?.message || "Unable to connect to the SOAR backend."
      );
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  useEffect(() => {
    loadSOARData();
  }, []);

  const categories = useMemo(() => {
    return [
      "All",
      ...new Set(workflows.map((workflow) => workflow.category)),
    ];
  }, [workflows]);

  const filteredWorkflows = useMemo(() => {
    const query = search.toLowerCase().trim();

    return workflows.filter((workflow) => {
      const searchableText = [
        workflow.id,
        workflow.name,
        workflow.description,
        workflow.category,
        workflow.trigger,
        workflow.status,
      ]
        .join(" ")
        .toLowerCase();

      const matchesSearch =
        !query || searchableText.includes(query);

      const matchesCategory =
        category === "All" || workflow.category === category;

      return matchesSearch && matchesCategory;
    });
  }, [workflows, search, category]);

  const activeCount = workflows.filter(
    (workflow) => workflow.status === "Active"
  ).length;

  const totalRuns = workflows.reduce(
    (total, workflow) => total + workflow.runs,
    0
  );

  const successRates = workflows
    .map((workflow) => workflow.successRate)
    .filter((rate) => rate > 0);

  const averageSuccessRate =
    successRates.length > 0
      ? (
          successRates.reduce((total, rate) => total + rate, 0) /
          successRates.length
        ).toFixed(1)
      : "—";

  const isSimulation =
    health?.simulation === true ||
    health?.simulation_only === true ||
    String(health?.mode || "").toLowerCase().includes("simulation");

  const runSOARAction = async (type) => {
    if (!selectedWorkflow?.id) return;

    setActionLoading(type);
    setActionMessage("");
    setActionError("");

    try {
      let response;

      if (type === "approve") {
        response = await approveSOARAction(selectedWorkflow.id, {
          approved_by: "ANALYST",
          approval_note: "Approved from SAOM-AI dashboard.",
        });
      }

      if (type === "reject") {
        response = await rejectSOARAction(selectedWorkflow.id, {
          rejected_by: "ANALYST",
          approval_note: "Rejected from SAOM-AI dashboard.",
        });
      }

      if (type === "execute") {
        response = await executeSOARAction(selectedWorkflow.id);
      }

      const responseData = unwrapResponse(response);

      setActionMessage(
        toText(
          getValue(responseData, ["message", "detail", "status"]),
          `SOAR action ${type} request completed.`
        )
      );

      await loadSOARData(true);
    } catch (requestError) {
      setActionError(
        requestError?.message ||
          `Unable to ${type} the selected SOAR action.`
      );
    } finally {
      setActionLoading("");
    }
  };

  const pendingCount = workflows.filter(
    (workflow) => workflow.status === "Pending"
  ).length;

  const executedCount = workflows.filter(
    (workflow) => workflow.status === "Executed"
  ).length;

  return (
    <AppShell connected={!error}>
      <PageHeader
        breadcrumb="Response"
        title="Automation"
        description="Playbook actions produced by the SOAR engine, their approval state and execution outcome."
        status={
          <div className="flex flex-wrap items-center gap-2">
            <Badge tone={healthError ? "slate" : "emerald"}>
              {healthError ? "Health unavailable" : "SOAR engine online"}
            </Badge>

            {isSimulation && <Badge tone="amber">Simulation mode</Badge>}
          </div>
        }
        actions={
          <>
            <Button
              variant="secondary"
              icon={RefreshCw}
              loading={refreshing}
              onClick={() => loadSOARData(true)}
              disabled={refreshing || loading}
            >
              Refresh
            </Button>

            <Button variant="primary" onClick={() => navigate("/approvals")}>
              Approval queue
            </Button>
          </>
        }
      />

      <div className="mx-auto max-w-[1600px] space-y-4 px-5 py-6 lg:px-8">
        {error && <Notice tone="error">{error}</Notice>}

        {healthError && <Notice tone="warning">{healthError}</Notice>}

        {actionMessage && (
          <Notice tone="success" onDismiss={() => setActionMessage("")}>
            {actionMessage}
          </Notice>
        )}

        {actionError && (
          <Notice tone="error" onDismiss={() => setActionError("")}>
            {actionError}
          </Notice>
        )}

        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
          <StatCard
            label="Waiting on approval"
            value={pendingCount}
            tone={pendingCount > 0 ? "medium" : "good"}
            emphasis
            hint="Blocked until an analyst decides"
            onClick={() => navigate("/approvals")}
          />

          <StatCard
            label="Active playbooks"
            value={activeCount}
            tone="brand"
            hint={`${executedCount} already executed`}
          />

          <StatCard
            label="Total executions"
            value={totalRuns}
            hint="Across every playbook"
          />

          <StatCard
            label="Average success rate"
            value={
              averageSuccessRate === "—"
                ? "—"
                : `${averageSuccessRate}%`
            }
            tone="good"
            hint="Reported by the SOAR engine"
          />
        </div>

        {/* ---------------------------------------------------- filter bar */}

        <div className="flex flex-col gap-2.5 rounded-xl border border-slate-200 bg-white p-3 lg:flex-row lg:items-center">
          <SearchInput
            value={search}
            onChange={(event) => setSearch(event.target.value)}
            placeholder="Search playbook, trigger or status"
            className="lg:max-w-sm lg:flex-1"
          />

          <SegmentedControl
            value={category}
            onChange={setCategory}
            options={categories}
          />

          <span className="text-xs tabular-nums text-slate-500 lg:ml-auto">
            {filteredWorkflows.length} of {workflows.length}
          </span>
        </div>

        {/* ------------------------------------------------ playbook list */}

        {loading ? (
          <Panel>
            <LoadingState label="Loading SOAR actions" rows={4} />
          </Panel>
        ) : filteredWorkflows.length === 0 ? (
          <Panel>
            <EmptyState
              icon={Workflow}
              title={
                workflows.length === 0
                  ? "No SOAR actions yet"
                  : "No playbooks match these filters"
              }
              description={
                workflows.length === 0
                  ? "Create a playbook from an incident, and the generated response actions appear here."
                  : "Clear the category filter or search for a different term."
              }
            />
          </Panel>
        ) : (
          <div className="grid gap-4 lg:grid-cols-2 2xl:grid-cols-3">
            {filteredWorkflows.map((workflow) => {
              const Icon = workflow.icon;

              return (
                <button
                  key={workflow.id}
                  type="button"
                  onClick={() => setSelectedWorkflow(workflow)}
                  className="flex flex-col rounded-xl border border-slate-200 bg-white p-5 text-left transition-colors duration-150 hover:border-slate-300 hover:bg-slate-50/60"
                >
                  <div className="flex items-start justify-between gap-3">
                    <div className="flex min-w-0 items-start gap-3">
                      <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg border border-slate-200 bg-slate-50 text-slate-600">
                        <Icon size={17} />
                      </span>

                      <div className="min-w-0">
                        <p className="truncate font-medium text-slate-900">
                          {workflow.name}
                        </p>

                        <p className="mt-0.5 truncate font-mono text-xs text-slate-500">
                          {workflow.id}
                        </p>
                      </div>
                    </div>

                    <StatusBadge status={workflow.status} />
                  </div>

                  <p className="mt-4 line-clamp-2 flex-1 text-sm leading-6 text-slate-500">
                    {workflow.description}
                  </p>

                  <div className="mt-4 flex flex-wrap items-center gap-2 border-t border-slate-100 pt-3.5">
                    <Badge tone={CATEGORY_TONE[workflow.category] || "slate"}>
                      {workflow.category}
                    </Badge>

                    <span className="text-xs text-slate-500">
                      Trigger: {workflow.trigger}
                    </span>

                    <span className="ml-auto text-xs tabular-nums text-slate-500">
                      {workflow.runs} runs
                    </span>
                  </div>
                </button>
              );
            })}
          </div>
        )}
      </div>

      {/* ------------------------------------------------- playbook panel */}

      <SidePanel
        open={Boolean(selectedWorkflow)}
        onClose={() => setSelectedWorkflow(null)}
        title={selectedWorkflow?.name}
        subtitle={selectedWorkflow?.id}
        footer={
          <div className="flex flex-wrap gap-2">
            <Button
              variant="success"
              icon={Check}
              loading={actionLoading === "approve"}
              disabled={Boolean(actionLoading)}
              onClick={() => runSOARAction("approve")}
            >
              Approve
            </Button>

            <Button
              variant="outlineDanger"
              icon={X}
              loading={actionLoading === "reject"}
              disabled={Boolean(actionLoading)}
              onClick={() => runSOARAction("reject")}
            >
              Reject
            </Button>

            <Button
              variant="primary"
              icon={Play}
              loading={actionLoading === "execute"}
              disabled={Boolean(actionLoading)}
              onClick={() => runSOARAction("execute")}
            >
              Execute
            </Button>
          </div>
        }
      >
        {selectedWorkflow && (
          <div className="space-y-6">
            <div className="flex flex-wrap items-center gap-2">
              <StatusBadge status={selectedWorkflow.status} />

              <Badge tone={CATEGORY_TONE[selectedWorkflow.category] || "slate"}>
                {selectedWorkflow.category}
              </Badge>

              {isSimulation && <Badge tone="amber">Simulation</Badge>}
            </div>

            <p className="text-sm leading-6 text-slate-700">
              {selectedWorkflow.description}
            </p>

            <div>
              <h3 className="mb-2.5 text-sm font-semibold text-slate-900">
                Response steps
              </h3>

              <ol className="space-y-2">
                {selectedWorkflow.actions.map((step, index) => (
                  <li
                    key={`${step}-${index}`}
                    className="flex items-start gap-3 rounded-lg border border-slate-200 bg-slate-50 px-3.5 py-2.5 text-sm text-slate-700"
                  >
                    <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-white text-[11px] font-semibold tabular-nums text-slate-500 ring-1 ring-slate-200">
                      {index + 1}
                    </span>

                    {step}
                  </li>
                ))}
              </ol>
            </div>

            <div>
              <h3 className="mb-1 text-sm font-semibold text-slate-900">
                Execution record
              </h3>

              <InfoRow label="Trigger" value={selectedWorkflow.trigger} />

              <InfoRow label="Runs" value={selectedWorkflow.runs} />

              <InfoRow
                label="Success rate"
                value={
                  selectedWorkflow.successRate > 0
                    ? `${selectedWorkflow.successRate}%`
                    : "Not reported"
                }
              />

              <InfoRow label="Last run" value={selectedWorkflow.lastRun} />

              {selectedWorkflow.approvedBy && (
                <InfoRow
                  label="Approved by"
                  value={toText(selectedWorkflow.approvedBy)}
                />
              )}

              {selectedWorkflow.approvalNote && (
                <InfoRow
                  label="Approval note"
                  value={toText(selectedWorkflow.approvalNote)}
                />
              )}
            </div>

            {selectedWorkflow.result && (
              <Card className="p-4">
                <p className="text-xs text-slate-500">Execution result</p>

                <p className="mt-1.5 text-sm leading-6 text-slate-800">
                  {toText(selectedWorkflow.result)}
                </p>
              </Card>
            )}
          </div>
        )}
      </SidePanel>
    </AppShell>
  );
}