
import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import {
  ArrowLeft,
  Workflow,
  Play,
  Pause,
  Plus,
  Search,
  CheckCircle2,
  AlertTriangle,
  Zap,
  ShieldCheck,
  Mail,
  Ban,
  UserCheck,
  RefreshCw,
  ChevronRight,
  Activity,
  X,
  Check,
  XCircle,
  Loader2,
  ShieldAlert,
} from "lucide-react";

import {
  getSOARActions,
  getSOARHealth,
  approveSOARAction,
  rejectSOARAction,
  executeSOARAction,
} from "../services/dashboardApi";

/* =========================================================
   HELPERS
========================================================= */

function unwrapResponse(response) {
  if (!response) return null;

  if (response.data !== undefined) {
    return response.data;
  }

  return response;
}

function getArrayFromResponse(response) {
  const data = unwrapResponse(response);

  if (Array.isArray(data)) return data;

  if (Array.isArray(data?.actions)) return data.actions;
  if (Array.isArray(data?.results)) return data.results;
  if (Array.isArray(data?.items)) return data.items;
  if (Array.isArray(data?.data)) return data.data;

  return [];
}

function getValue(object, keys, fallback = "") {
  for (const key of keys) {
    const value = object?.[key];

    if (value !== undefined && value !== null && value !== "") {
      return value;
    }
  }

  return fallback;
}

function toNumber(value, fallback = 0) {
  const number = Number(value);
  return Number.isFinite(number) ? number : fallback;
}

function toText(value, fallback = "—") {
  if (value === undefined || value === null || value === "") {
    return fallback;
  }

  if (typeof value === "object") {
    return JSON.stringify(value);
  }

  return String(value);
}

function normalizeStatus(value) {
  const status = String(value || "").toLowerCase();

  if (
    status.includes("pause") ||
    status.includes("disabled") ||
    status.includes("inactive")
  ) {
    return "Paused";
  }

  if (
    status.includes("approve") ||
    status.includes("pending") ||
    status.includes("review")
  ) {
    return "Pending";
  }

  if (
    status.includes("complete") ||
    status.includes("execut") ||
    status.includes("success")
  ) {
    return "Executed";
  }

  return "Active";
}

function normalizeCategory(value) {
  const category = String(value || "").toLowerCase();

  if (category.includes("network") || category.includes("ip")) {
    return "Network Security";
  }

  if (
    category.includes("identity") ||
    category.includes("account") ||
    category.includes("user")
  ) {
    return "Identity Security";
  }

  if (
    category.includes("notification") ||
    category.includes("email") ||
    category.includes("notify")
  ) {
    return "Notifications";
  }

  return "Endpoint Response";
}

function getIconForCategory(category) {
  if (category === "Network Security") return Ban;
  if (category === "Identity Security") return UserCheck;
  if (category === "Notifications") return Mail;

  return ShieldCheck;
}

function normalizeActions(value) {
  if (Array.isArray(value)) {
    return value.map((item) => {
      if (typeof item === "string") return item;

      return toText(
        getValue(item, ["name", "action", "type", "description"], "Response action")
      );
    });
  }

  if (typeof value === "string" && value.trim()) {
    return value
      .split(/[,|\n]/)
      .map((item) => item.trim())
      .filter(Boolean);
  }

  return [];
}

function normalizeWorkflow(item, index) {
  const category = normalizeCategory(
    getValue(item, ["category", "type", "action_type", "module"])
  );

  const rawStatus = getValue(item, [
    "status",
    "state",
    "approval_status",
    "execution_status",
  ]);

  const runs = toNumber(
    getValue(item, [
      "runs",
      "executions",
      "execution_count",
      "total_executions",
      "run_count",
    ]),
    0
  );

  const successRate = toNumber(
    getValue(item, ["successRate", "success_rate", "success_percentage"]),
    0
  );

  const actions = normalizeActions(
    getValue(item, ["actions", "response_actions", "steps", "playbook_steps"])
  );

  return {
    ...item,
    id: toText(
      getValue(item, ["id", "action_id", "playbook_id", "workflow_id"]),
      `SOAR-${String(index + 1).padStart(3, "0")}`
    ),
    name: toText(
      getValue(item, [
        "name",
        "title",
        "action_name",
        "playbook_name",
        "workflow_name",
      ]),
      `SOAR Response Action ${index + 1}`
    ),
    description: toText(
      getValue(item, ["description", "summary", "details"]),
      "Security response action generated by the SOAR engine."
    ),
    category,
    trigger: toText(
      getValue(item, [
        "trigger",
        "trigger_type",
        "event_type",
        "alert_type",
        "condition",
      ]),
      "Security alert"
    ),
    actions:
      actions.length > 0
        ? actions
        : ["Review security alert", "Execute response action", "Record result"],
    status: normalizeStatus(rawStatus),
    runs,
    lastRun: toText(
      getValue(item, ["lastRun", "last_run", "executed_at", "updated_at"]),
      "Not executed yet"
    ),
    successRate,
    icon: getIconForCategory(category),
    rawStatus: rawStatus || "",
    approvedBy: getValue(item, ["approved_by", "approvedBy"]),
    approvalNote: getValue(item, ["approval_note", "approvalNote"]),
    result: getValue(item, ["result", "execution_result", "message"]),
  };
}

/* =========================================================
   STYLES / SMALL COMPONENTS
========================================================= */

const categoryStyles = {
  "Endpoint Response":
    "text-cyan-300 bg-cyan-400/10 border-cyan-400/20",
  "Network Security":
    "text-purple-300 bg-purple-400/10 border-purple-400/20",
  Notifications:
    "text-orange-300 bg-orange-400/10 border-orange-400/20",
  "Identity Security":
    "text-emerald-300 bg-emerald-400/10 border-emerald-400/20",
};

function Badge({ children, className = "" }) {
  return (
    <span
      className={`inline-flex items-center rounded-full border px-2.5 py-1 text-xs font-semibold ${className}`}
    >
      {children}
    </span>
  );
}

function StatCard({ label, value, icon: Icon, tone = "cyan" }) {
  const tones = {
    cyan: "bg-cyan-400/10 text-cyan-400",
    green: "bg-emerald-400/10 text-emerald-400",
    orange: "bg-orange-400/10 text-orange-400",
    purple: "bg-purple-400/10 text-purple-400",
  };

  return (
    <div className="rounded-2xl border border-white/10 bg-[#111a2b] p-4">
      <div className="flex items-center justify-between">
        <span className="text-xs text-slate-400">{label}</span>

        <div className={`rounded-xl p-2 ${tones[tone]}`}>
          <Icon size={17} />
        </div>
      </div>

      <p className="mt-3 text-2xl font-bold text-white">{value}</p>
    </div>
  );
}

function ActionButton({
  children,
  onClick,
  disabled = false,
  loading = false,
  className = "",
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      disabled={disabled || loading}
      className={`inline-flex items-center justify-center gap-2 rounded-xl px-3 py-2.5 text-sm font-semibold transition disabled:cursor-not-allowed disabled:opacity-50 ${className}`}
    >
      {loading && <Loader2 size={15} className="animate-spin" />}
      {children}
    </button>
  );
}

/* =========================================================
   PAGE
========================================================= */

export default function Automation() {
  const navigate = useNavigate();

  const [workflows, setWorkflows] = useState([]);
  const [selectedWorkflow, setSelectedWorkflow] = useState(null);

  const [search, setSearch] = useState("");
  const [category, setCategory] = useState("All");

  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState("");

  const [health, setHealth] = useState(null);
  const [healthError, setHealthError] = useState("");

  const [actionLoading, setActionLoading] = useState("");
  const [actionMessage, setActionMessage] = useState("");
  const [actionError, setActionError] = useState("");

  const loadSOARData = async (showRefreshState = false) => {
    if (showRefreshState) {
      setRefreshing(true);
    } else {
      setLoading(true);
    }

    setError("");
    setHealthError("");

    try {
      const [actionsResponse, healthResponse] = await Promise.allSettled([
        getSOARActions(),
        getSOARHealth(),
      ]);

      if (actionsResponse.status === "fulfilled") {
        const normalized = getArrayFromResponse(actionsResponse.value).map(
          normalizeWorkflow
        );

        setWorkflows(normalized);

        setSelectedWorkflow((current) => {
          if (!current) return null;

          return (
            normalized.find((workflow) => workflow.id === current.id) || null
          );
        });
      } else {
        setError(
          actionsResponse.reason?.message ||
            "Unable to load SOAR actions from the backend."
        );
      }

      if (healthResponse.status === "fulfilled") {
        setHealth(unwrapResponse(healthResponse.value));
      } else {
        setHealthError("SOAR health status unavailable.");
      }
    } catch (requestError) {
      setError(
        requestError?.message || "Unable to connect to the SOAR backend."
      );
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  useEffect(() => {
    loadSOARData();
  }, []);

  const categories = useMemo(() => {
    return [
      "All",
      ...new Set(workflows.map((workflow) => workflow.category)),
    ];
  }, [workflows]);

  const filteredWorkflows = useMemo(() => {
    const query = search.toLowerCase().trim();

    return workflows.filter((workflow) => {
      const searchableText = [
        workflow.id,
        workflow.name,
        workflow.description,
        workflow.category,
        workflow.trigger,
        workflow.status,
      ]
        .join(" ")
        .toLowerCase();

      const matchesSearch =
        !query || searchableText.includes(query);

      const matchesCategory =
        category === "All" || workflow.category === category;

      return matchesSearch && matchesCategory;
    });
  }, [workflows, search, category]);

  const activeCount = workflows.filter(
    (workflow) => workflow.status === "Active"
  ).length;

  const totalRuns = workflows.reduce(
    (total, workflow) => total + workflow.runs,
    0
  );

  const successRates = workflows
    .map((workflow) => workflow.successRate)
    .filter((rate) => rate > 0);

  const averageSuccessRate =
    successRates.length > 0
      ? (
          successRates.reduce((total, rate) => total + rate, 0) /
          successRates.length
        ).toFixed(1)
      : "—";

  const isSimulation =
    health?.simulation === true ||
    health?.simulation_only === true ||
    String(health?.mode || "").toLowerCase().includes("simulation");

  const runSOARAction = async (type) => {
    if (!selectedWorkflow?.id) return;

    setActionLoading(type);
    setActionMessage("");
    setActionError("");

    try {
      let response;

      if (type === "approve") {
        response = await approveSOARAction(selectedWorkflow.id, {
          approved_by: "ANALYST",
          approval_note: "Approved from SAOM-AI dashboard.",
        });
      }

      if (type === "reject") {
        response = await rejectSOARAction(selectedWorkflow.id, {
          rejected_by: "ANALYST",
          approval_note: "Rejected from SAOM-AI dashboard.",
        });
      }

      if (type === "execute") {
        response = await executeSOARAction(selectedWorkflow.id);
      }

      const responseData = unwrapResponse(response);

      setActionMessage(
        toText(
          getValue(responseData, ["message", "detail", "status"]),
          `SOAR action ${type} request completed.`
        )
      );

      await loadSOARData(true);
    } catch (requestError) {
      setActionError(
        requestError?.message ||
          `Unable to ${type} the selected SOAR action.`
      );
    } finally {
      setActionLoading("");
    }
  };

  return (
    <div className="min-h-screen bg-[#08111f] px-4 py-6 text-white sm:px-6 lg:px-8">
      <div className="mx-auto max-w-[1600px]">
        {/* Header */}
        <div className="mb-6 flex flex-col justify-between gap-4 lg:flex-row lg:items-center">
          <div>
            <button
              type="button"
              onClick={() => navigate("/dashboard")}
              className="mb-3 inline-flex items-center gap-2 text-sm text-slate-400 transition hover:text-cyan-400"
            >
              <ArrowLeft size={16} />
              Back to Dashboard
            </button>

            <div className="flex items-center gap-3">
              <div className="rounded-2xl bg-cyan-400/10 p-3 text-cyan-400">
                <Workflow size={28} />
              </div>

              <div>
                <h1 className="text-2xl font-bold tracking-tight sm:text-3xl">
                  SOAR Automation
                </h1>

                <p className="mt-1 text-sm text-slate-400">
                  Automate security response workflows and reduce manual effort.
                </p>
              </div>
            </div>
          </div>

          <button
            type="button"
            onClick={() =>
              setActionError(
                "Custom workflow creation is not available in the current backend yet."
              )
            }
            className="inline-flex items-center justify-center gap-2 rounded-xl bg-cyan-400 px-4 py-2.5 text-sm font-bold text-[#06111e] transition hover:bg-cyan-300"
          >
            <Plus size={17} />
            Create Workflow
          </button>
        </div>

        {/* Backend status */}
        <div className="mb-6 flex flex-wrap items-center gap-3">
          <Badge
            className={
              healthError
                ? "border-orange-400/20 bg-orange-400/10 text-orange-300"
                : isSimulation
                ? "border-yellow-400/20 bg-yellow-400/10 text-yellow-300"
                : "border-emerald-400/20 bg-emerald-400/10 text-emerald-300"
            }
          >
            <span className="mr-2 h-1.5 w-1.5 rounded-full bg-current" />
            {healthError
              ? "SOAR STATUS UNKNOWN"
              : isSimulation
              ? "SOAR ENGINE · SIMULATION"
              : "SOAR ENGINE ONLINE"}
          </Badge>

          {health?.mode && (
            <span className="text-xs text-slate-500">
              Mode: {toText(health.mode)}
            </span>
          )}
        </div>

        {/* Messages */}
        {error && (
          <div className="mb-6 flex items-start gap-3 rounded-2xl border border-red-400/20 bg-red-400/10 p-4 text-sm text-red-200">
            <AlertTriangle size={18} className="mt-0.5 shrink-0" />
            <div className="flex-1">{error}</div>

            <button
              type="button"
              onClick={() => setError("")}
              className="text-red-300 hover:text-white"
            >
              <X size={16} />
            </button>
          </div>
        )}

        {actionMessage && (
          <div className="mb-6 flex items-start gap-3 rounded-2xl border border-emerald-400/20 bg-emerald-400/10 p-4 text-sm text-emerald-200">
            <CheckCircle2 size={18} className="mt-0.5 shrink-0" />
            <div className="flex-1">{actionMessage}</div>

            <button
              type="button"
              onClick={() => setActionMessage("")}
              className="text-emerald-300 hover:text-white"
            >
              <X size={16} />
            </button>
          </div>
        )}

        {actionError && (
          <div className="mb-6 flex items-start gap-3 rounded-2xl border border-orange-400/20 bg-orange-400/10 p-4 text-sm text-orange-200">
            <AlertTriangle size={18} className="mt-0.5 shrink-0" />
            <div className="flex-1">{actionError}</div>

            <button
              type="button"
              onClick={() => setActionError("")}
              className="text-orange-300 hover:text-white"
            >
              <X size={16} />
            </button>
          </div>
        )}

        {/* Stats */}
        <div className="mb-6 grid grid-cols-2 gap-4 lg:grid-cols-4">
          <StatCard
            label="Total Actions"
            value={loading ? "—" : workflows.length}
            icon={Workflow}
          />

          <StatCard
            label="Active Actions"
            value={loading ? "—" : activeCount}
            icon={Zap}
            tone="green"
          />

          <StatCard
            label="Total Executions"
            value={loading ? "—" : totalRuns}
            icon={Activity}
            tone="purple"
          />

          <StatCard
            label="Average Success Rate"
            value={loading ? "—" : `${averageSuccessRate}${averageSuccessRate !== "—" ? "%" : ""}`}
            icon={CheckCircle2}
            tone="orange"
          />
        </div>

        {/* Filters */}
        <div className="mb-6 flex flex-col gap-3 rounded-2xl border border-white/10 bg-[#0d1727] p-4 lg:flex-row">
          <div className="relative flex-1">
            <Search
              size={17}
              className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500"
            />

            <input
              value={search}
              onChange={(event) => setSearch(event.target.value)}
              placeholder="Search workflows or SOAR actions..."
              className="w-full rounded-xl border border-white/10 bg-[#111a2b] py-2.5 pl-10 pr-3 text-sm text-white outline-none transition placeholder:text-slate-500 focus:border-cyan-400/60"
            />
          </div>

          <select
            value={category}
            onChange={(event) => setCategory(event.target.value)}
            className="rounded-xl border border-white/10 bg-[#111a2b] px-3 py-2.5 text-sm text-slate-300 outline-none focus:border-cyan-400/60"
          >
            {categories.map((item) => (
              <option key={item} value={item}>
                {item}
              </option>
            ))}
          </select>

          <button
            type="button"
            onClick={() => loadSOARData(true)}
            disabled={refreshing}
            className="inline-flex items-center justify-center gap-2 rounded-xl border border-cyan-400/30 px-4 py-2.5 text-sm font-semibold text-cyan-300 transition hover:bg-cyan-400/10 disabled:opacity-50"
          >
            <RefreshCw
              size={16}
              className={refreshing ? "animate-spin" : ""}
            />
            Refresh
          </button>
        </div>

        <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_390px]">
          {/* Action cards */}
          <section>
            <div className="mb-4 flex items-center justify-between">
              <h2 className="text-sm font-bold uppercase tracking-wider text-white">
                SOAR Response Actions
              </h2>

              <span className="text-xs text-slate-500">
                {filteredWorkflows.length} actions
              </span>
            </div>

            {loading ? (
              <div className="rounded-2xl border border-white/10 bg-[#111a2b] p-10 text-center">
                <Loader2
                  size={28}
                  className="mx-auto animate-spin text-cyan-400"
                />
                <p className="mt-3 text-sm text-slate-400">
                  Loading SOAR actions from backend...
                </p>
              </div>
            ) : (
              <div className="grid gap-4 lg:grid-cols-2">
                {filteredWorkflows.map((workflow) => {
                  const Icon = workflow.icon;
                  const isActive = workflow.status === "Active";
                  const isSelected = selectedWorkflow?.id === workflow.id;

                  return (
                    <div
                      key={workflow.id}
                      className={`rounded-2xl border bg-[#111a2b] p-5 transition ${
                        isSelected
                          ? "border-cyan-400/60"
                          : "border-white/10 hover:border-cyan-400/30"
                      }`}
                    >
                      <div className="mb-4 flex items-start justify-between gap-3">
                        <div className="rounded-xl bg-cyan-400/10 p-3 text-cyan-400">
                          <Icon size={23} />
                        </div>

                        <Badge
                          className={
                            isActive
                              ? "border-emerald-400/20 bg-emerald-400/10 text-emerald-300"
                              : workflow.status === "Pending"
                              ? "border-yellow-400/20 bg-yellow-400/10 text-yellow-300"
                              : "border-orange-400/20 bg-orange-400/10 text-orange-300"
                          }
                        >
                          {workflow.status}
                        </Badge>
                      </div>

                      <p className="mb-2 text-[11px] font-semibold tracking-wider text-slate-500">
                        {workflow.id}
                      </p>

                      <h3 className="text-base font-bold text-white">
                        {workflow.name}
                      </h3>

                      <p className="mt-2 min-h-[60px] text-sm leading-6 text-slate-400">
                        {workflow.description}
                      </p>

                      <div className="mt-4">
                        <Badge
                          className={
                            categoryStyles[workflow.category] ||
                            categoryStyles["Endpoint Response"]
                          }
                        >
                          {workflow.category}
                        </Badge>
                      </div>

                      <div className="mt-5 grid grid-cols-2 gap-3 border-y border-white/10 py-4">
                        <div>
                          <p className="text-xs text-slate-500">Executions</p>
                          <p className="mt-1 text-lg font-bold text-white">
                            {workflow.runs}
                          </p>
                        </div>

                        <div>
                          <p className="text-xs text-slate-500">
                            Success Rate
                          </p>
                          <p className="mt-1 text-lg font-bold text-emerald-400">
                            {workflow.successRate > 0
                              ? `${workflow.successRate}%`
                              : "—"}
                          </p>
                        </div>
                      </div>

                      <div className="mt-4 flex flex-wrap gap-2">
                        <ActionButton
                          onClick={() => setSelectedWorkflow(workflow)}
                          className="flex-1 border border-white/10 text-slate-300 hover:border-cyan-400/40 hover:text-cyan-300"
                        >
                          View Details
                          <ChevronRight size={16} />
                        </ActionButton>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}

            {!loading && filteredWorkflows.length === 0 && (
              <div className="rounded-2xl border border-dashed border-white/10 p-10 text-center text-sm text-slate-500">
                No SOAR actions match your search.
              </div>
            )}
          </section>

          {/* Details */}
          <aside className="space-y-6">
            <section className="rounded-2xl border border-white/10 bg-[#111a2b] p-5">
              <div className="mb-5 flex items-center gap-2">
                <Workflow size={18} className="text-cyan-400" />

                <h2 className="text-sm font-bold uppercase tracking-wider">
                  Action Details
                </h2>
              </div>

              {selectedWorkflow ? (
                <div>
                  <div className="mb-4 flex items-start justify-between gap-3">
                    <div>
                      <p className="text-xs text-slate-500">
                        {selectedWorkflow.id}
                      </p>

                      <h3 className="mt-1 text-lg font-bold text-white">
                        {selectedWorkflow.name}
                      </h3>
                    </div>

                    <button
                      type="button"
                      onClick={() => setSelectedWorkflow(null)}
                      className="text-slate-500 transition hover:text-white"
                    >
                      <X size={17} />
                    </button>
                  </div>

                  <div className="mb-4">
                    <p className="mb-2 text-xs font-semibold uppercase tracking-wider text-slate-500">
                      Trigger
                    </p>

                    <div className="rounded-xl border border-white/10 bg-[#0d1727] p-3 text-sm text-cyan-300">
                      {selectedWorkflow.trigger}
                    </div>
                  </div>

                  <div className="mb-4">
                    <p className="mb-2 text-xs font-semibold uppercase tracking-wider text-slate-500">
                      Response Actions
                    </p>

                    <div className="space-y-2">
                      {selectedWorkflow.actions.map((action, index) => (
                        <div
                          key={`${selectedWorkflow.id}-${index}`}
                          className="flex items-center gap-3 rounded-xl border border-white/10 bg-[#0d1727] p-3"
                        >
                          <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-cyan-400/10 text-xs font-bold text-cyan-300">
                            {index + 1}
                          </span>

                          <span className="text-sm text-slate-300">
                            {action}
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>

                  {selectedWorkflow.approvedBy && (
                    <div className="mb-4 rounded-xl border border-white/10 bg-[#0d1727] p-3 text-xs text-slate-400">
                      Approved by:{" "}
                      <span className="text-slate-200">
                        {toText(selectedWorkflow.approvedBy)}
                      </span>
                    </div>
                  )}

                  {selectedWorkflow.result && (
                    <div className="mb-4 rounded-xl border border-white/10 bg-[#0d1727] p-3 text-xs text-slate-400">
                      Result:
                      <p className="mt-1 break-words text-slate-200">
                        {toText(selectedWorkflow.result)}
                      </p>
                    </div>
                  )}

                  <div className="grid grid-cols-1 gap-2 sm:grid-cols-3 xl:grid-cols-1">
                    <ActionButton
                      onClick={() => runSOARAction("approve")}
                      loading={actionLoading === "approve"}
                      disabled={Boolean(actionLoading)}
                      className="border border-emerald-400/20 bg-emerald-400/10 text-emerald-300 hover:bg-emerald-400/20"
                    >
                      <Check size={16} />
                      Approve
                    </ActionButton>

                    <ActionButton
                      onClick={() => runSOARAction("reject")}
                      loading={actionLoading === "reject"}
                      disabled={Boolean(actionLoading)}
                      className="border border-red-400/20 bg-red-400/10 text-red-300 hover:bg-red-400/20"
                    >
                      <XCircle size={16} />
                      Reject
                    </ActionButton>

                    <ActionButton
                      onClick={() => runSOARAction("execute")}
                      loading={actionLoading === "execute"}
                      disabled={Boolean(actionLoading)}
                      className="bg-cyan-400 text-[#06111e] hover:bg-cyan-300"
                    >
                      <Play size={16} />
                      Execute
                    </ActionButton>
                  </div>
                </div>
              ) : (
                <div className="rounded-xl border border-dashed border-white/10 bg-[#0d1727] p-6 text-center">
                  <Workflow
                    className="mx-auto text-slate-600"
                    size={30}
                  />

                  <p className="mt-3 text-sm text-slate-400">
                    Select a SOAR action to view its trigger, response steps,
                    and available backend controls.
                  </p>
                </div>
              )}
            </section>

            {/* Backend information */}
            <section className="rounded-2xl border border-white/10 bg-[#111a2b] p-5">
              <div className="mb-4 flex items-center gap-2">
                <ShieldAlert size={18} className="text-cyan-400" />

                <h2 className="text-sm font-bold uppercase tracking-wider">
                  Backend Information
                </h2>
              </div>

              <div className="space-y-3 text-sm">
                <div className="flex items-center justify-between gap-3">
                  <span className="text-slate-500">Service</span>
                  <span className="text-slate-200">
                    {toText(health?.service, "SOAR")}
                  </span>
                </div>

                <div className="flex items-center justify-between gap-3">
                  <span className="text-slate-500">Mode</span>
                  <span
                    className={
                      isSimulation
                        ? "text-yellow-300"
                        : "text-emerald-300"
                    }
                  >
                    {toText(health?.mode, "Unknown")}
                  </span>
                </div>

                <div className="flex items-center justify-between gap-3">
                  <span className="text-slate-500">Actions loaded</span>
                  <span className="text-slate-200">
                    {workflows.length}
                  </span>
                </div>
              </div>

              {isSimulation && (
                <div className="mt-4 rounded-xl border border-yellow-400/20 bg-yellow-400/10 p-3 text-xs leading-5 text-yellow-200">
                  Simulation mode is enabled. Approve, reject, and execute
                  requests may simulate security actions instead of changing
                  real infrastructure.
                </div>
              )}
            </section>

            {/* Recent activity */}
            <section className="rounded-2xl border border-white/10 bg-[#111a2b] p-5">
              <div className="mb-5 flex items-center gap-2">
                <RefreshCw size={18} className="text-cyan-400" />

                <h2 className="text-sm font-bold uppercase tracking-wider">
                  Recent Activity
                </h2>
              </div>

              {workflows.length === 0 ? (
                <p className="text-sm text-slate-500">
                  No recent SOAR activity available.
                </p>
              ) : (
                <div className="space-y-4">
                  {workflows.slice(0, 5).map((workflow) => (
                    <div
                      key={`activity-${workflow.id}`}
                      className="border-b border-white/10 pb-4 last:border-0 last:pb-0"
                    >
                      <div className="flex items-start gap-3">
                        <div className="rounded-lg bg-cyan-400/10 p-2 text-cyan-400">
                          <Activity size={16} />
                        </div>

                        <div className="min-w-0 flex-1">
                          <p className="text-sm font-semibold text-white">
                            {workflow.name}
                          </p>

                          <p className="mt-1 text-xs text-slate-500">
                            {workflow.lastRun}
                          </p>
                        </div>

                        <Badge className="border-white/10 bg-white/5 text-slate-300">
                          {workflow.status}
                        </Badge>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </section>
          </aside>
        </div>
      </div>
    </div>
  );
}